<a href="https://colab.research.google.com/github/vinodhramu/AI-102-AIEngineer/blob/master/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental TensorFlow operations
- Introduction to Tensors
- Getting infoirmation from tensors
- Manipulating tensors
- Tensors and Numpy
- using @tf.function (a way to speed up regular python functions)
- using GPus with TensorFlow
- Exercise

# Tensors
- Tensor as multi dimensional numerical representation
- It could be numbers,image,text


In [2]:
import tensorflow as tf
print(tf.__version__)

2.7.0


# Creating Tensor with tf.constant()

We will not create tensors manually because Tensorflow has modules built in such us tf.io , tf.data which read data source and convert them into tensors.

To get familiar with tensors and manipulate them we will create ourselves.

In [3]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

A Scalar is known as rank 0 tensor as it has no dimensions

Tensor can have unlimited range of dimensions

In [4]:
# check number of dimensions of tensor (ndim stands for number of dimensions)
scalar.ndim 

0

In [5]:
# Create a Vector (more than 0 dimension)
V = tf.constant([10,10])
V

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
V.ndim

1

In [7]:
# Create a matrix (more than 1 dimension)

M = tf.constant([[10,7],[7,10]])
M

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
M.ndim

2

By Default TensorFlow creates with either int32 or float32 datatype

In [9]:
# Create another matrix and define datatype

M2 = tf.constant([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float16)
M2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [10]:
M2.ndim

2

In [11]:
M3 = tf.constant([
                  [
                   [1,2],[1,4]
                  ],
                   [
                    [3,4],[2,5]
                    ]
                  ])
M3

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 4]],

       [[3, 4],
        [2, 5]]], dtype=int32)>

In [12]:
M3.ndim

3

This Dimension is Rank of Tensor
Above M3 is Rank 3 Tensor.

# Create tensor using tf.Variable()

Difference between tf.constant() and tf.Variable is 
- tensors created using **tf.constant** is *immutable* 
- tensors created using **tf.Variable** is *mutable*



In [13]:
# Create the same tensor with both variable and constant

changeable_tensor = tf.Variable([10,20])
Unchangeable_tensor = tf.constant([10,20])

changeable_tensor,Unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>)

Try changing elements in changeable tensor

In [14]:
changeable_tensor[0]=30

TypeError: ignored

To change an element in tf.Variable() tensor requires tf.assign()

In [15]:
changeable_tensor[0].assign(30)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([30, 20], dtype=int32)>

In [16]:
Unchangeable_tensor[0].assign(100)
Unchangeable_tensor

AttributeError: ignored

# Creating random tensors

Random tensors are of some arbitrary size which contains random numbers.

We can create random tensors by using **tf.random.Generator** class


In [17]:
# Creating Random tensors with same seed
random_tensors1 = tf.random.Generator.from_seed(30)
random_tensors1 = random_tensors1.normal(shape=(3,3))

random_tensors2 = tf.random.Generator.from_seed(30)
random_tensors2 = random_tensors2.normal(shape=(3,3))

random_tensors1,random_tensors2, random_tensors1==random_tensors2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.8357487 ,  0.20849545,  1.4040174 ],
        [-2.735283  ,  1.2232229 , -1.8653691 ],
        [ 0.00511209, -1.0493753 ,  0.7901182 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.8357487 ,  0.20849545,  1.4040174 ],
        [-2.735283  ,  1.2232229 , -1.8653691 ],
        [ 0.00511209, -1.0493753 ,  0.7901182 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [18]:
random_tensors3 = tf.random.Generator.from_seed(3)
random_tensors3 = random_tensors3.normal(shape=(3,3))

random_tensors1==random_tensors3

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False],
       [False, False, False]])>

What if we want to shuffle the order of tensors??

Why we should need shuffling??

If we have 100 images of Apples and Oranges. First 60 images are apple and remaing 40 or oranges. this order wil affect neural network learning. its good to shuffle the data.

In [19]:
# Shuffle a tensor using using inbuilt method

Original_data = tf.constant([[1,2],[3,4]])

# Gets different results each time
tf.random.shuffle(Original_data)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [20]:
# Shuffle in same order everytime using seed.
tf.random.shuffle(Original_data,seed=20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2]], dtype=int32)>

tf.random.set_seed(40) sets global seed

tf.random.shuffle(seed=40) sets Operational seed

# Other ways to create tensors

- We can use tf.ones() to create tensors of all ones
- We can use t.zeros() to create tensors of all zeros



In [21]:
# Make tensors of all ones
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
# Make a tensor of all zeros
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

We can turn Numpy array to tensors

But Tensors can run on GPUs

- Tensors or Matrix represented by Capital Letters
- Vectors represented by Small Letters

In [24]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
A= tf.constant(numpy_A,shape=(2,3,4))
numpy_A,A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [27]:
# Get various attributes of tensor
print("Datatype of every element:", A.dtype)
print("Number of dimensions (rank):", A.ndim)
print("Shape of tensor:", A.shape)
print("Elements along axis 0 of tensor:", A.shape[0])
print("Elements along last axis of tensor:", A.shape[-1])
print("Total number of elements (2*3*4):", tf.size(A).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 3
Shape of tensor: (2, 3, 4)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 4
Total number of elements (2*3*4): 24


Indexing Tensors like Python

In [29]:
# Get first 2 elements in each dimension
A[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int32)>